#167377536: Signup validation middleware
andela/vali-ah-backend pull request #17
Opened 2019-07-29 15:29 UTC by Jonathan4github

#### What does this PR do?
This pull request implements a signup validation middleware
#### Description of Task to be completed

- create a validator folder
- implement a signup validation functionality
- write tests for signup validation

#### How should this be manually tested?

- git clone branch
- cd to project directory
- run npm install && run npm test

#### Any Background Context You want to provide?

#### What are the relevant pivotal tracker stories?

[#167377536](https://pivotaltracker.com/story/show/167377536)

#### Screenshots (if appropriate)
N/A
#### Questions:

2019-07-29 17:09 UTC, Bastieno commented on src/middlewares/validators/AuthValidator.js
> +   * @param {object} res - request object
Fixed this:
res - response object

2019-07-29 17:13 UTC, Jonathan4github commented on src/middlewares/validators/AuthValidator.js
> +   * @param {object} res - request object
> Fixed this:
> res - response object

Noted

2019-07-29 17:37 UTC, Bastieno approved these changes
This looks good!

2019-07-30 16:39 UTC, Merkll approved these changes

2019-07-30 16:39 UTC, Merkll commented on .vscode/launch.json
> +        {
add this file to .gitignore

2019-07-30 16:39 UTC, Merkll commented on src/middlewares/validators/AuthValidator.js
> +      errorMessage.characters = 'Password must be alphanumeric characters';
can we look into express-validator or joi?

2019-07-30 16:39 UTC, Merkll commented on tests/auth.test.js
> +      .send(invalidFirstname)
can use asyn/await

2019-08-01 15:28 UTC, iverenshaguy requested changes
Please review my comments

2019-08-01 15:28 UTC, iverenshaguy commented on package.json
> +    "test": "mocha --require @babel/register --require regenerator-runtime tests/**test.js --exit",
Please fix this line

2019-08-01 15:28 UTC, iverenshaguy commented on src/middlewares/AuthValidator.js
> +  * @param {object} request - request object
Ensure your JSDoc adheres to our team convention as discussed this morning. Also, next is not a type, it should be a function ie. `@param {Function} next - calls next middleware`

2019-08-01 15:28 UTC, iverenshaguy commented on src/routes/auth.js
> +import signupValidator from '../middlewares/AuthValidator';
We will need a validator middleware that will interface with the different validators for each route. Please look into this.

2019-08-01 15:28 UTC, iverenshaguy commented on src/middlewares/AuthValidator.js
> +  const errors = request.validationErrors();
I don't like this file. It needs to be refactored to have one validation middleware that validates all routes based on the different field validators.

2019-08-01 15:28 UTC, iverenshaguy commented on tests/auth.test.js
> +} from './mockData/mockUser';
Please change the `mockData` folder to the `fixtures` folder. Tests fixtures sound better than `mockData`.

2019-08-01 15:28 UTC, iverenshaguy commented on tests/routes/auth.test.js
> -
Please leave the new line

2019-08-01 15:52 UTC, Jonathan4github commented on tests/routes/auth.test.js
> -
Thanks for the feedback working on it.

2019-08-02 13:54 UTC, iverenshaguy requested changes
You've done a fantastic job. Kindly review my comments so that we can merge

2019-08-02 13:54 UTC, iverenshaguy commented on src/middlewares/validator.js
> +  const schemaTovalidate = schemas || [];
Really good job. Please update to 
```suggestion
  const schemaToValidate = schemas || [];
```

2019-08-02 13:54 UTC, iverenshaguy commented on src/middlewares/validator.js
> + * @returns {object} returns response message
```suggestion
 * @returns {Array} array of validation schema and middleware
```

2019-08-02 13:54 UTC, iverenshaguy commented on src/middlewares/validator.js
> +      return response.status(status).json(mappedErrors);
What format is this error in? Please make sure it follows our convention and drop a snippet of the format here

2019-08-02 13:54 UTC, iverenshaguy commented on src/routes/auth.js
> +
Any reason for the newlines after the documentation?

2019-08-02 14:48 UTC, iverenshaguy approved these changes

2019-08-02 14:56 UTC, merged