167377549 Create user notification system
andela/vali-ah-backend pull request #28
Opened 2019-08-07 03:28 UTC by Merkll

#### What does this PR do?
This pull request creates an email and in-app notification system for user activities

#### Description of Task to be completed
- create notification for user-related activities
- schedules notification for batch email sending
- implement batched email notification
- implement in-app notification using socket.io

#### How should this be manually tested?

#### Any Background Context You want to provide?
N/A

#### What are the relevant pivotal tracker stories?

[#167377549](https://pivotaltracker.com/story/show/167377549)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2019-08-07 10:53 UTC, ibkadeeko requested changes

2019-08-07 10:53 UTC, ibkadeeko commented on src/services/notification.js
> +  addNotification(type, notificationHandler) {
Great Job. Please go through your Js Docs, I believe we are to have `@functions` stated based on our team convention

2019-08-07 14:46 UTC, kennyedward approved these changes
This looks good to me.

2019-08-07 15:00 UTC, ibkadeeko approved these changes

2019-08-08 10:28 UTC, iverenshaguy approved these changes
I see a very very good work here. Well done. Please check my review comments and update your PR so that I can merge it

2019-08-08 10:28 UTC, iverenshaguy commented on src/helpers/models.js
> +export const QueryPagination = async (sourceFunction, dataToFunction = {}, size = 50) => {
This is not a Class or a Model, it's a helper and should have a camelCased name. Please fix all functions in this file

2019-08-08 10:28 UTC, iverenshaguy commented on src/services/email.js
> + * @return {Promise} - Returns a promise that get resolved to a success object
Thanks for correcting

2019-08-08 10:28 UTC, iverenshaguy commented on src/services/email.js
>      if (!template) throw new Error('Email Template not available');
```suggestion
    if (!template) throw new Error('Email template not available');
```

2019-08-08 10:41 UTC, merged